/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ta_java;

// import org.junit.jupiter.api.Test;
// import static org.junit.jupiter.api.Assertions.*;

// class AppTest {
//     @Test void appHasAGreeting() {
//         App classUnderTest = new App();
//         assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
//     }
// }


// package com.howtodoinjava.demo;

import ta_java.events.employeeMgmt.AddEmployeeEvent;
import ta_java.exception.ApplicationException;
import ta_java.listeners.EmployeeEventsListener;
import ta_java.model.Employee;
import ta_java.service.EmployeeService;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.event.ApplicationEvents;
import org.springframework.test.context.event.RecordApplicationEvents;

@SpringBootTest
@RecordApplicationEvents
public class AppTest {

  @Autowired
  private ApplicationEvents applicationEvents;

  @Autowired
  private EmployeeService employeeService;

  @Autowired
  private EmployeeEventsListener employeeEventsListener;

  @Test
  void employeeCreationShouldPublishEvent() throws ApplicationException {

    employeeService.create(new Employee("Alex"));

    Assertions.assertEquals(1, applicationEvents
        .stream(AddEmployeeEvent.class)
        .filter(event -> event.getEmployee().getName().equals("Alex"))
        .count());

    // There are multiple events recorded such as PrepareInstanceEvent,
    // BeforeTestMethodEvent, BeforeTestExecutionEvent, AddEmployeeEvent etc.
    applicationEvents.stream(AddEmployeeEvent.class).forEach(System.out::println);

    // employeeEventsListener.
  }
}
// EmployeeEventsListener