/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ta_java;

// import org.junit.jupiter.api.Test;
// import static org.junit.jupiter.api.Assertions.*;

// class AppTest {
//     @Test void appHasAGreeting() {
//         App classUnderTest = new App();
//         assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
//     }
// }


// package com.howtodoinjava.demo;

import ta_java.events.stockManagement.UpdateStockEvent;
import ta_java.exception.ApplicationException;
import ta_java.listeners.StockEventsListener;
import ta_java.model.Stock;
import ta_java.service.StockService;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.event.ApplicationEvents;
import org.springframework.test.context.event.RecordApplicationEvents;
import java.util.*;

@SpringBootTest
@RecordApplicationEvents
public class AppTest {

  @Autowired
  private ApplicationEvents applicationEvents;

  @Autowired
  private StockService stockService;

  @Autowired
  private StockEventsListener stockEventsListener;

  @Test
  void employeeCreationShouldPublishEvent() throws ApplicationException {

    List<Stock> stocks = new ArrayList<>();
    stockService.updateMultiple(stocks);

    Assertions.assertEquals(stocks.size(), 0
    // applicationEvents
    //     .stream(UpdateStockEvent.class)
    //     .filter(event -> event.getPrice())
    //     .count()
        );

    // There are multiple events recorded such as PrepareInstanceEvent,
    // BeforeTestMethodEvent, BeforeTestExecutionEvent, AddEmployeeEvent etc.
    // applicationEvents.stream(AddEmployeeEvent.class).forEach(System.out::println);

    // employeeEventsListener.
  }
}
// EmployeeEventsListener